export const itemImageMapping: Record<string, string> = {
  "acid": "/images/resources/Acid.png",
  "air_pollution": "/images/resources/Air Pollution.png",
  "aluminum": "/images/resources/Aluminum.png",
  "ammonia": "/images/resources/Ammonia.png",
  "anesthetics": "/images/resources/Anesthetics.png",
  "antibiotics": "/images/resources/Antibiotics.png",
  "bauxite": "/images/resources/Bauxite.png",
  "bedrock": "/images/resources/Bedrock.png",
  "bread": "/images/resources/Bread.png",
  "brine": "/images/resources/Brine.png",
  "broken_glass": "/images/resources/Broken Glass.png",
  "burner_solid": "/images/resources/Burner (Solid).png",
  "cake": "/images/resources/Cake.png",
  "canola": "/images/resources/Canola.png",
  "carbon_dioxide": "/images/resources/Carbon Dioxide.png",
  "cement": "/images/resources/Cement.png",
  "chicken_carcass": "/images/resources/Chicken Carcass.png",
  "chicken": "/images/resources/Chicken.png",
  "chilled_water": "/images/resources/Chilled Water.png",
  "chlorine": "/images/resources/Chlorine.png",
  "coal": "/images/resources/Coal.png",
  "concrete_crushed": "/images/resources/Concrete Crushed.png",
  "concrete_slab": "/images/resources/Concrete Slab.png",
  "concretecrushed": "/images/resources/ConcreteCrushed.png",
  "construction_parts_ii": "/images/resources/Construction Parts II.png",
  "construction_parts_iii": "/images/resources/Construction Parts III.png",
  "construction_parts_iv": "/images/resources/Construction Parts IV.png",
  "construction_parts": "/images/resources/Construction Parts.png",
  "consumer_electronics": "/images/resources/Consumer Electronics.png",
  "cooking_oil": "/images/resources/Cooking Oil.png",
  "copper_ore_crushed": "/images/resources/Copper Ore Crushed.png",
  "copper_ore": "/images/resources/Copper Ore.png",
  "copper_scrap": "/images/resources/Copper Scrap.png",
  "copper": "/images/resources/Copper.png",
  "corn_mash": "/images/resources/Corn Mash.png",
  "corn": "/images/resources/Corn.png",
  "crude_oil": "/images/resources/Crude Oil.png",
  "diesel": "/images/resources/Diesel.png",
  "digestate": "/images/resources/Digestate.png",
  "dirt": "/images/resources/Dirt.png",
  "drugs": "/images/resources/Drugs.png",
  "electricity": "/images/resources/Electricity.png",
  "electronics_ii": "/images/resources/Electronics II.png",
  "electronics_iii": "/images/resources/Electronics III.png",
  "electronics": "/images/resources/Electronics.png",
  "exhaust": "/images/resources/Exhaust.png",
  "fertility": "/images/resources/Fertility.png",
  "filter_media": "/images/resources/Filter Media.png",
  "flour": "/images/resources/Flour.png",
  "flowers": "/images/resources/Flowers.png",
  "food_pack": "/images/resources/Food Pack.png",
  "food": "/images/resources/Food.png",
  "fruit": "/images/resources/Fruit.png",
  "fruits": "/images/resources/Fruits.png",
  "fuel_gas": "/images/resources/Fuel Gas.png",
  "glass_mix": "/images/resources/Glass Mix.png",
  "glass": "/images/resources/Glass.png",
  "gold_ore_concentrate": "/images/resources/Gold Ore Concentrate.png",
  "gold_ore_crushed": "/images/resources/Gold Ore Crushed.png",
  "gold_ore_powder": "/images/resources/Gold Ore Powder.png",
  "gold_ore": "/images/resources/Gold Ore.png",
  "gold_scrap": "/images/resources/Gold Scrap.png",
  "gold": "/images/resources/Gold.png",
  "graphite": "/images/resources/Graphite.png",
  "gravel": "/images/resources/Gravel.png",
  "greenmanure": "/images/resources/GreenManure.png",
  "heavy_oil": "/images/resources/Heavy Oil.png",
  "household_appliances": "/images/resources/Household Appliances.png",
  "household_electronics": "/images/resources/Household Electronics.png",
  "household_goods": "/images/resources/Household Goods.png",
  "hydrogen_fluoride": "/images/resources/Hydrogen Fluoride.png",
  "hydrogen": "/images/resources/Hydrogen.png",
  "impure_copper": "/images/resources/Impure Copper.png",
  "iron_ore_crushed": "/images/resources/Iron Ore Crushed.png",
  "iron_ore": "/images/resources/Iron Ore.png",
  "iron_scrap": "/images/resources/Iron Scrap.png",
  "iron": "/images/resources/Iron.png",
  "lab_equipment_ii": "/images/resources/Lab Equipment II.png",
  "lab_equipment_iii": "/images/resources/Lab Equipment III.png",
  "lab_equipment_iv": "/images/resources/Lab Equipment IV.png",
  "lab_equipment": "/images/resources/Lab Equipment.png",
  "land_rest": "/images/resources/Land Rest.png",
  "light_oil": "/images/resources/Light Oil.png",
  "limestone": "/images/resources/Limestone.png",
  "maintenance_i": "/images/resources/Maintenance I.png",
  "maintenance_ii": "/images/resources/Maintenance II.png",
  "maintenance_iii": "/images/resources/Maintenance III.png",
  "meat": "/images/resources/Meat.png",
  "mechanical_parts": "/images/resources/Mechanical Parts.png",
  "mechanical_power": "/images/resources/Mechanical Power.png",
  "medical_equipment": "/images/resources/Medical Equipment.png",
  "medical_supplies_ii": "/images/resources/Medical Supplies II.png",
  "medical_supplies_iii": "/images/resources/Medical Supplies III.png",
  "medical_supplies": "/images/resources/Medical Supplies.png",
  "medium_oil": "/images/resources/Medium Oil.png",
  "metal_scrap": "/images/resources/Metal Scrap.png",
  "microchips_stage_1_a": "/images/resources/Microchips Stage 1 A.png",
  "microchips_stage_1_b": "/images/resources/Microchips Stage 1 B.png",
  "microchips_stage_1_c": "/images/resources/Microchips Stage 1 C.png",
  "microchips_stage_2_a": "/images/resources/Microchips Stage 2 A.png",
  "microchips_stage_2_b": "/images/resources/Microchips Stage 2 B.png",
  "microchips_stage_2_c": "/images/resources/Microchips Stage 2 C.png",
  "microchips_stage_3_a": "/images/resources/Microchips Stage 3 A.png",
  "microchips_stage_3_b": "/images/resources/Microchips Stage 3 B.png",
  "microchips_stage_3_c": "/images/resources/Microchips Stage 3 C.png",
  "microchips_stage_4_a": "/images/resources/Microchips Stage 4 A.png",
  "microchips_stage_4_b": "/images/resources/Microchips Stage 4 B.png",
  "microchips": "/images/resources/Microchips.png",
  "molten_aluminum": "/images/resources/Molten Aluminum.png",
  "molten_copper": "/images/resources/Molten Copper.png",
  "molten_glass": "/images/resources/Molten Glass.png",
  "molten_iron": "/images/resources/Molten Iron.png",
  "molten_silicon": "/images/resources/Molten Silicon.png",
  "molten_steel": "/images/resources/Molten Steel.png",
  "morphine": "/images/resources/Morphine.png",
  "naphtha": "/images/resources/Naphtha.png",
  "nitrogen": "/images/resources/Nitrogen.png",
  "oxygen": "/images/resources/Oxygen.png",
  "pcb": "/images/resources/PCB.png",
  "plastic": "/images/resources/Plastic.png",
  "poppy": "/images/resources/Poppy.png",
  "population": "/images/resources/Population.png",
  "potato": "/images/resources/Potato.png",
  "quartz": "/images/resources/Quartz.png",
  "recyclables": "/images/resources/Recyclables.png",
  "rock": "/images/resources/Rock.png",
  "rubber": "/images/resources/Rubber.png",
  "salt": "/images/resources/Salt.png",
  "sand": "/images/resources/Sand.png",
  "sausage": "/images/resources/Sausage.png",
  "seawater": "/images/resources/Seawater.png",
  "server": "/images/resources/Server.png",
  "silicon_poly": "/images/resources/Silicon (Poly).png",
  "silicon_wafer": "/images/resources/Silicon Wafer.png",
  "slag_crushed": "/images/resources/Slag Crushed.png",
  "slag": "/images/resources/Slag.png",
  "sludge": "/images/resources/Sludge.png",
  "snack": "/images/resources/Snack.png",
  "solar_cell_mono": "/images/resources/Solar Cell Mono.png",
  "solar_cell": "/images/resources/Solar Cell.png",
  "sour_water": "/images/resources/Sour Water.png",
  "spent_fuel": "/images/resources/Spent Fuel.png",
  "stacker": "/images/resources/Stacker.png",
  "steam_high_old": "/images/resources/Steam (High) (old).png",
  "steam_low": "/images/resources/Steam (Low).png",
  "steam_depleted": "/images/resources/Steam Depleted.png",
  "steel": "/images/resources/Steel.png",
  "sugar_cane": "/images/resources/Sugar Cane.png",
  "sugar": "/images/resources/Sugar.png",
  "sulfur": "/images/resources/Sulfur.png",
  "tflops": "/images/resources/Tflops.png",
  "tofu": "/images/resources/Tofu.png",
  "toxic_slurry": "/images/resources/Toxic Slurry.png",
  "uranium_ore_crushed": "/images/resources/Uranium Ore Crushed.png",
  "uranium_ore": "/images/resources/Uranium Ore.png",
  "uranium_pellets": "/images/resources/Uranium Pellets.png",
  "uranium_rod": "/images/resources/Uranium Rod.png",
  "vegetables": "/images/resources/Vegetables.png",
  "vehicle_parts_iii": "/images/resources/Vehicle Parts III.png",
  "waste_water": "/images/resources/Waste Water.png",
  "waste": "/images/resources/Waste.png",
  "water_pollution": "/images/resources/Water Pollution.png",
  "water": "/images/resources/Water.png",
  "wheat": "/images/resources/Wheat.png",
  "wood": "/images/resources/Wood.png",
  "yellow_cake": "/images/resources/Yellow Cake.png",
};

export const coiItemsWithImages = [
  { id: "acid", name: "Acid", image: "/images/resources/Acid.png" },
  { id: "air_pollution", name: "Air Pollution", image: "/images/resources/Air Pollution.png" },
  { id: "aluminum", name: "Aluminum", image: "/images/resources/Aluminum.png" },
  { id: "ammonia", name: "Ammonia", image: "/images/resources/Ammonia.png" },
  { id: "anesthetics", name: "Anesthetics", image: "/images/resources/Anesthetics.png" },
  { id: "antibiotics", name: "Antibiotics", image: "/images/resources/Antibiotics.png" },
  { id: "bauxite", name: "Bauxite", image: "/images/resources/Bauxite.png" },
  { id: "bedrock", name: "Bedrock", image: "/images/resources/Bedrock.png" },
  { id: "bread", name: "Bread", image: "/images/resources/Bread.png" },
  { id: "brine", name: "Brine", image: "/images/resources/Brine.png" },
  { id: "broken_glass", name: "Broken Glass", image: "/images/resources/Broken Glass.png" },
  { id: "burner_solid", name: "Burner (Solid)", image: "/images/resources/Burner (Solid).png" },
  { id: "cake", name: "Cake", image: "/images/resources/Cake.png" },
  { id: "canola", name: "Canola", image: "/images/resources/Canola.png" },
  { id: "carbon_dioxide", name: "Carbon Dioxide", image: "/images/resources/Carbon Dioxide.png" },
  { id: "cement", name: "Cement", image: "/images/resources/Cement.png" },
  { id: "chicken_carcass", name: "Chicken Carcass", image: "/images/resources/Chicken Carcass.png" },
  { id: "chicken", name: "Chicken", image: "/images/resources/Chicken.png" },
  { id: "chilled_water", name: "Chilled Water", image: "/images/resources/Chilled Water.png" },
  { id: "chlorine", name: "Chlorine", image: "/images/resources/Chlorine.png" },
  { id: "coal", name: "Coal", image: "/images/resources/Coal.png" },
  { id: "concrete_crushed", name: "Concrete Crushed", image: "/images/resources/Concrete Crushed.png" },
  { id: "concrete_slab", name: "Concrete Slab", image: "/images/resources/Concrete Slab.png" },
  { id: "concretecrushed", name: "ConcreteCrushed", image: "/images/resources/ConcreteCrushed.png" },
  { id: "construction_parts_ii", name: "Construction Parts II", image: "/images/resources/Construction Parts II.png" },
  { id: "construction_parts_iii", name: "Construction Parts III", image: "/images/resources/Construction Parts III.png" },
  { id: "construction_parts_iv", name: "Construction Parts IV", image: "/images/resources/Construction Parts IV.png" },
  { id: "construction_parts", name: "Construction Parts", image: "/images/resources/Construction Parts.png" },
  { id: "consumer_electronics", name: "Consumer Electronics", image: "/images/resources/Consumer Electronics.png" },
  { id: "cooking_oil", name: "Cooking Oil", image: "/images/resources/Cooking Oil.png" },
  { id: "copper_ore_crushed", name: "Copper Ore Crushed", image: "/images/resources/Copper Ore Crushed.png" },
  { id: "copper_ore", name: "Copper Ore", image: "/images/resources/Copper Ore.png" },
  { id: "copper_scrap", name: "Copper Scrap", image: "/images/resources/Copper Scrap.png" },
  { id: "copper", name: "Copper", image: "/images/resources/Copper.png" },
  { id: "corn_mash", name: "Corn Mash", image: "/images/resources/Corn Mash.png" },
  { id: "corn", name: "Corn", image: "/images/resources/Corn.png" },
  { id: "crude_oil", name: "Crude Oil", image: "/images/resources/Crude Oil.png" },
  { id: "diesel", name: "Diesel", image: "/images/resources/Diesel.png" },
  { id: "digestate", name: "Digestate", image: "/images/resources/Digestate.png" },
  { id: "dirt", name: "Dirt", image: "/images/resources/Dirt.png" },
  { id: "drugs", name: "Drugs", image: "/images/resources/Drugs.png" },
  { id: "electricity", name: "Electricity", image: "/images/resources/Electricity.png" },
  { id: "electronics_ii", name: "Electronics II", image: "/images/resources/Electronics II.png" },
  { id: "electronics_iii", name: "Electronics III", image: "/images/resources/Electronics III.png" },
  { id: "electronics", name: "Electronics", image: "/images/resources/Electronics.png" },
  { id: "exhaust", name: "Exhaust", image: "/images/resources/Exhaust.png" },
  { id: "fertility", name: "Fertility", image: "/images/resources/Fertility.png" },
  { id: "filter_media", name: "Filter Media", image: "/images/resources/Filter Media.png" },
  { id: "flour", name: "Flour", image: "/images/resources/Flour.png" },
  { id: "flowers", name: "Flowers", image: "/images/resources/Flowers.png" },
  { id: "food_pack", name: "Food Pack", image: "/images/resources/Food Pack.png" },
  { id: "food", name: "Food", image: "/images/resources/Food.png" },
  { id: "fruit", name: "Fruit", image: "/images/resources/Fruit.png" },
  { id: "fruits", name: "Fruits", image: "/images/resources/Fruits.png" },
  { id: "fuel_gas", name: "Fuel Gas", image: "/images/resources/Fuel Gas.png" },
  { id: "glass_mix", name: "Glass Mix", image: "/images/resources/Glass Mix.png" },
  { id: "glass", name: "Glass", image: "/images/resources/Glass.png" },
  { id: "gold_ore_concentrate", name: "Gold Ore Concentrate", image: "/images/resources/Gold Ore Concentrate.png" },
  { id: "gold_ore_crushed", name: "Gold Ore Crushed", image: "/images/resources/Gold Ore Crushed.png" },
  { id: "gold_ore_powder", name: "Gold Ore Powder", image: "/images/resources/Gold Ore Powder.png" },
  { id: "gold_ore", name: "Gold Ore", image: "/images/resources/Gold Ore.png" },
  { id: "gold_scrap", name: "Gold Scrap", image: "/images/resources/Gold Scrap.png" },
  { id: "gold", name: "Gold", image: "/images/resources/Gold.png" },
  { id: "graphite", name: "Graphite", image: "/images/resources/Graphite.png" },
  { id: "gravel", name: "Gravel", image: "/images/resources/Gravel.png" },
  { id: "greenmanure", name: "GreenManure", image: "/images/resources/GreenManure.png" },
  { id: "heavy_oil", name: "Heavy Oil", image: "/images/resources/Heavy Oil.png" },
  { id: "household_appliances", name: "Household Appliances", image: "/images/resources/Household Appliances.png" },
  { id: "household_electronics", name: "Household Electronics", image: "/images/resources/Household Electronics.png" },
  { id: "household_goods", name: "Household Goods", image: "/images/resources/Household Goods.png" },
  { id: "hydrogen_fluoride", name: "Hydrogen Fluoride", image: "/images/resources/Hydrogen Fluoride.png" },
  { id: "hydrogen", name: "Hydrogen", image: "/images/resources/Hydrogen.png" },
  { id: "impure_copper", name: "Impure Copper", image: "/images/resources/Impure Copper.png" },
  { id: "iron_ore_crushed", name: "Iron Ore Crushed", image: "/images/resources/Iron Ore Crushed.png" },
  { id: "iron_ore", name: "Iron Ore", image: "/images/resources/Iron Ore.png" },
  { id: "iron_scrap", name: "Iron Scrap", image: "/images/resources/Iron Scrap.png" },
  { id: "iron", name: "Iron", image: "/images/resources/Iron.png" },
  { id: "lab_equipment_ii", name: "Lab Equipment II", image: "/images/resources/Lab Equipment II.png" },
  { id: "lab_equipment_iii", name: "Lab Equipment III", image: "/images/resources/Lab Equipment III.png" },
  { id: "lab_equipment_iv", name: "Lab Equipment IV", image: "/images/resources/Lab Equipment IV.png" },
  { id: "lab_equipment", name: "Lab Equipment", image: "/images/resources/Lab Equipment.png" },
  { id: "land_rest", name: "Land Rest", image: "/images/resources/Land Rest.png" },
  { id: "light_oil", name: "Light Oil", image: "/images/resources/Light Oil.png" },
  { id: "limestone", name: "Limestone", image: "/images/resources/Limestone.png" },
  { id: "maintenance_i", name: "Maintenance I", image: "/images/resources/Maintenance I.png" },
  { id: "maintenance_ii", name: "Maintenance II", image: "/images/resources/Maintenance II.png" },
  { id: "maintenance_iii", name: "Maintenance III", image: "/images/resources/Maintenance III.png" },
  { id: "meat", name: "Meat", image: "/images/resources/Meat.png" },
  { id: "mechanical_parts", name: "Mechanical Parts", image: "/images/resources/Mechanical Parts.png" },
  { id: "mechanical_power", name: "Mechanical Power", image: "/images/resources/Mechanical Power.png" },
  { id: "medical_equipment", name: "Medical Equipment", image: "/images/resources/Medical Equipment.png" },
  { id: "medical_supplies_ii", name: "Medical Supplies II", image: "/images/resources/Medical Supplies II.png" },
  { id: "medical_supplies_iii", name: "Medical Supplies III", image: "/images/resources/Medical Supplies III.png" },
  { id: "medical_supplies", name: "Medical Supplies", image: "/images/resources/Medical Supplies.png" },
  { id: "medium_oil", name: "Medium Oil", image: "/images/resources/Medium Oil.png" },
  { id: "metal_scrap", name: "Metal Scrap", image: "/images/resources/Metal Scrap.png" },
  { id: "microchips_stage_1_a", name: "Microchips Stage 1 A", image: "/images/resources/Microchips Stage 1 A.png" },
  { id: "microchips_stage_1_b", name: "Microchips Stage 1 B", image: "/images/resources/Microchips Stage 1 B.png" },
  { id: "microchips_stage_1_c", name: "Microchips Stage 1 C", image: "/images/resources/Microchips Stage 1 C.png" },
  { id: "microchips_stage_2_a", name: "Microchips Stage 2 A", image: "/images/resources/Microchips Stage 2 A.png" },
  { id: "microchips_stage_2_b", name: "Microchips Stage 2 B", image: "/images/resources/Microchips Stage 2 B.png" },
  { id: "microchips_stage_2_c", name: "Microchips Stage 2 C", image: "/images/resources/Microchips Stage 2 C.png" },
  { id: "microchips_stage_3_a", name: "Microchips Stage 3 A", image: "/images/resources/Microchips Stage 3 A.png" },
  { id: "microchips_stage_3_b", name: "Microchips Stage 3 B", image: "/images/resources/Microchips Stage 3 B.png" },
  { id: "microchips_stage_3_c", name: "Microchips Stage 3 C", image: "/images/resources/Microchips Stage 3 C.png" },
  { id: "microchips_stage_4_a", name: "Microchips Stage 4 A", image: "/images/resources/Microchips Stage 4 A.png" },
  { id: "microchips_stage_4_b", name: "Microchips Stage 4 B", image: "/images/resources/Microchips Stage 4 B.png" },
  { id: "microchips", name: "Microchips", image: "/images/resources/Microchips.png" },
  { id: "molten_aluminum", name: "Molten Aluminum", image: "/images/resources/Molten Aluminum.png" },
  { id: "molten_copper", name: "Molten Copper", image: "/images/resources/Molten Copper.png" },
  { id: "molten_glass", name: "Molten Glass", image: "/images/resources/Molten Glass.png" },
  { id: "molten_iron", name: "Molten Iron", image: "/images/resources/Molten Iron.png" },
  { id: "molten_silicon", name: "Molten Silicon", image: "/images/resources/Molten Silicon.png" },
  { id: "molten_steel", name: "Molten Steel", image: "/images/resources/Molten Steel.png" },
  { id: "morphine", name: "Morphine", image: "/images/resources/Morphine.png" },
  { id: "naphtha", name: "Naphtha", image: "/images/resources/Naphtha.png" },
  { id: "nitrogen", name: "Nitrogen", image: "/images/resources/Nitrogen.png" },
  { id: "oxygen", name: "Oxygen", image: "/images/resources/Oxygen.png" },
  { id: "pcb", name: "PCB", image: "/images/resources/PCB.png" },
  { id: "plastic", name: "Plastic", image: "/images/resources/Plastic.png" },
  { id: "poppy", name: "Poppy", image: "/images/resources/Poppy.png" },
  { id: "population", name: "Population", image: "/images/resources/Population.png" },
  { id: "potato", name: "Potato", image: "/images/resources/Potato.png" },
  { id: "quartz", name: "Quartz", image: "/images/resources/Quartz.png" },
  { id: "recyclables", name: "Recyclables", image: "/images/resources/Recyclables.png" },
  { id: "rock", name: "Rock", image: "/images/resources/Rock.png" },
  { id: "rubber", name: "Rubber", image: "/images/resources/Rubber.png" },
  { id: "salt", name: "Salt", image: "/images/resources/Salt.png" },
  { id: "sand", name: "Sand", image: "/images/resources/Sand.png" },
  { id: "sausage", name: "Sausage", image: "/images/resources/Sausage.png" },
  { id: "seawater", name: "Seawater", image: "/images/resources/Seawater.png" },
  { id: "server", name: "Server", image: "/images/resources/Server.png" },
  { id: "silicon_poly", name: "Silicon (Poly)", image: "/images/resources/Silicon (Poly).png" },
  { id: "silicon_wafer", name: "Silicon Wafer", image: "/images/resources/Silicon Wafer.png" },
  { id: "slag_crushed", name: "Slag Crushed", image: "/images/resources/Slag Crushed.png" },
  { id: "slag", name: "Slag", image: "/images/resources/Slag.png" },
  { id: "sludge", name: "Sludge", image: "/images/resources/Sludge.png" },
  { id: "snack", name: "Snack", image: "/images/resources/Snack.png" },
  { id: "solar_cell_mono", name: "Solar Cell Mono", image: "/images/resources/Solar Cell Mono.png" },
  { id: "solar_cell", name: "Solar Cell", image: "/images/resources/Solar Cell.png" },
  { id: "sour_water", name: "Sour Water", image: "/images/resources/Sour Water.png" },
  { id: "spent_fuel", name: "Spent Fuel", image: "/images/resources/Spent Fuel.png" },
  { id: "stacker", name: "Stacker", image: "/images/resources/Stacker.png" },
  { id: "steam_high_old", name: "Steam (High) (old)", image: "/images/resources/Steam (High) (old).png" },
  { id: "steam_low", name: "Steam (Low)", image: "/images/resources/Steam (Low).png" },
  { id: "steam_depleted", name: "Steam Depleted", image: "/images/resources/Steam Depleted.png" },
  { id: "steel", name: "Steel", image: "/images/resources/Steel.png" },
  { id: "sugar_cane", name: "Sugar Cane", image: "/images/resources/Sugar Cane.png" },
  { id: "sugar", name: "Sugar", image: "/images/resources/Sugar.png" },
  { id: "sulfur", name: "Sulfur", image: "/images/resources/Sulfur.png" },
  { id: "tflops", name: "Tflops", image: "/images/resources/Tflops.png" },
  { id: "tofu", name: "Tofu", image: "/images/resources/Tofu.png" },
  { id: "toxic_slurry", name: "Toxic Slurry", image: "/images/resources/Toxic Slurry.png" },
  { id: "uranium_ore_crushed", name: "Uranium Ore Crushed", image: "/images/resources/Uranium Ore Crushed.png" },
  { id: "uranium_ore", name: "Uranium Ore", image: "/images/resources/Uranium Ore.png" },
  { id: "uranium_pellets", name: "Uranium Pellets", image: "/images/resources/Uranium Pellets.png" },
  { id: "uranium_rod", name: "Uranium Rod", image: "/images/resources/Uranium Rod.png" },
  { id: "vegetables", name: "Vegetables", image: "/images/resources/Vegetables.png" },
  { id: "vehicle_parts_iii", name: "Vehicle Parts III", image: "/images/resources/Vehicle Parts III.png" },
  { id: "waste_water", name: "Waste Water", image: "/images/resources/Waste Water.png" },
  { id: "waste", name: "Waste", image: "/images/resources/Waste.png" },
  { id: "water_pollution", name: "Water Pollution", image: "/images/resources/Water Pollution.png" },
  { id: "water", name: "Water", image: "/images/resources/Water.png" },
  { id: "wheat", name: "Wheat", image: "/images/resources/Wheat.png" },
  { id: "wood", name: "Wood", image: "/images/resources/Wood.png" },
  { id: "yellow_cake", name: "Yellow Cake", image: "/images/resources/Yellow Cake.png" },
];